### ISSUE TITLE
Does this support latexmk?

### ISSUE THREAD

**Issue by krishnakumarg1984** [arsinh/uni-stuttgart-phdthesis-template#1]
Do you support ```latexmk``` builds?

I like continuous compilation upon every save which is supported by the ```-pvc``` options passed to ```latexmk```. 

It would be awesome if you could investigate support for this.

**Comment by valentjn** [comment]
I'm currently writing my own thesis and as written in the `README`, there isn't really support for anything that isn't deemed useful for my purposes :smile:

The reason which I prefer SCons over latexmk is that SCons can additionally handle automated graphics generation via the Python scripts in `gfx/py/`. Each of those scripts generate a variable number of PDFs (standalone images), saving them in `build/gfx/`. SCons detects if a script has changed, and regenerates the corresponding PDF image automatically (and of course the main thesis PDF).

latexmk is designed only for the `lualatex` -> `biber` -> `lualatex` etc. cycle, not for external dependencies like these "scripted" images. There are also some external `*.lua` files, which I think latexmk cannot handle as dependencies as well.

Another related problem with latexmk is the lack of flexibility. latexmk supports neither `TEXINPUTS` nor `\graphicspath`, which makes it difficult to compile in another directory while not touching the `tex/` at all...

However, I've hacked something together in a new `Makefile`. The "solution" is copy everything into the `build/tex/` directory and then run latexmk in there. You can enable your `-pvc` option, but then you'd have to be cautious and only edit the `*.tex` files in `build/tex/`, not those in `tex/`, as they won't be recopied when changed.

If you've got better ideas, then feel free to write something yourself and open a PR.
